name: pos_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  mobile_scanner: ^6.0.2
  fl_chart: ^0.65.0 # Use the latest version
  url_launcher: ^6.1.10 # Use the latest stable version
  font_awesome_flutter: ^10.1.0
  # Keep these only if you plan to use PDF printing alongside Bluetooth
  printing: ^5.11.1
  pdf: ^3.10.8
  shared_preferences: ^2.2.2 # Or the latest stable version
  # --- FIX APPLIED HERE ---
  flutter_bluetooth_printer: ^2.0.0 # Handles Bluetooth connection and sending data
  #  esc_pos_utils: ^1.1.1 # âœ… CORRECTED: Using a valid, stable 1.x.x version
  esc_pos_utils_plus: ^2.0.4 # Or the latest stable version
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.0
  multi_select_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
#  fonts:
#    - family: NotoSansMyanmar
#      fonts:
#        - asset: assets/fonts/NotoSansMyanmar-Regular.ttf
